### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by Jetski5822** [almbox/vsts-ssis-extension#39]
Hey Chaps, 

Great plugin, just wondered about the license,. At the moment you have it listed as we cant use it for anything other than personal use, any chance to open this up and let people who need to use in in companies use it? or is there a different paid model?

Cheers, Nick

**Comment by tinuverma** [comment]
Has anyone heard on license?

**Comment by Jetski5822** [comment]
Fraid not 😟

**Comment by tinuverma** [comment]
oh well, then I won't be using it :(

**Comment by Jetski5822** [comment]
I did this...

```
steps:
- task: CmdLine@1
  displayName: 'Build SSIS'
  inputs:
	filename: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Devenv.com"'
	arguments: '"$(Build.SourcesDirectory)\$(Solution)" /rebuild $(SSISBuildConfiguration) /project "$(Build.SourcesDirectory)\src\SomeProject\SomeProject.dtproj"'
```

That should replace it :)
